export const SHOES_LIST = {
    GET_SHOES_LIST: 'GET_SHOES_LIST',
    SET_SHOES_LIST: 'SET_SHOES_LIST',
    GET_SHOES_LIST_ERROR: 'GET_SHOES_LIST_ERROR',
    GET_SHOES_ITEMS: 'GET_SHOE_ITEMS',
    SET_SHOES_ITEMS: 'SET_SHOES_ITEMS',
    GET_SHOES_ITEMS_ERROR: 'GET_SHOES_ITEMS_ERROR',
    GET_SHOE_ID: 'GET_SHOE_ID',
    SET_SHOE_ID:'SET_SHOE_ID',
    SET_SHOE_ID_ERROR: 'SET_SHOE_ID_ERROR',
}